name: Eclipse Build Non-Working

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"
      
      
      - name: Try Running Java Application
        run: |
            cd MIDIPianoSheetCreator
            java -jar MIDIPianoSheetCreator.jar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-build
          path: |
            out/artifacts/MIDIPianoSheetCreator_custom.jar
